### ISSUE TITLE
Node.js Africa Suggesting a way forward

### ISSUE THREAD

**Issue by inidaname** [nodejsafrica/admin#5]
### Disclaimer

_These are completely based on personal observation and recommendation, feel free to make corrections on the comment section, I am also aware that some of my suggestions are already effected._

## Definition

In the Organization's definition: Node.js Africa is an Open Source Organization. As an **Open Source Organization**, our model of government should be an open government model where by issues, PR, meeting documents, suggestions, proposal or other related topics are addressed openly and collectively, including but not limited to announcements for all upcoming meetings and preparations for related events.

## Membership and Node Users

**Membership** and **Node Users** these are two categories we could approach to attract widespread acceptance.

### Membership

Membership should be open to the public but may be categorized as _Individuals_ and _Organizations_, it's okay if criteria are given as to whom become a member of the organization but I would suggest no restrictions. I suggest Node.Js Africa members should not primarily be restricted to only Africans, external support will go a long way in promoting what we hope to achieve.

### Node.js Users/Advocate

Individuals who may not want be identified as a member or may not meet up with the criteria could register as a Node User/Advocate but may be categorized as _Individuals_ and _Organizations_, in this case this could be restricted to be Africans only.

### The result and purpose of this

It will create a database collection of Node.Js community and supporters in Africa

## Guides for creating Repos and Merging PRs

**Merging PRs**: Creating files and documents should only be by creating a branch on the repo and sending a PR which should not merge until approved by at least a quorum of Board Members at a meeting or on the repo this will give other room for participation of all members and understanding of activities, importantly it will help manage a good document presentation.

Creating Repos for this Org should be agreed upon at a Board Meeting where by at least a quorum is available to understand what the repo stands to represent.

_I will add more in the comment section as I remember_

**Comment by codeekage** [comment]
According to the COC, this has been opened for too long and I am pushing forward with this to a PR. 
Thank you team 🙏
