### ISSUE TITLE
Node.js Board Meeting 2019/04/03

### ISSUE THREAD

**Issue by inidaname** [nodejsafrica/admin#8]
## Time
**18:00HRS**

## Link
https://zoom.us/j/289168691
## Agenda
 - Confirm time and days of the bi-weekly recurring board meeting
 - Identifying roles, activities, and responsibilities to assign for incoming volunteers
 - Other items from Google Docs Road Map.

## Invited
All Board members
@codeekage @chukundah @OpesanyaAdebayo @inidaname 

_Feel free to add any agenda that should be discussed_

## Minutes of Previous meeting
[Board Meeting 2019-03-20](https://github.com/nodejsafrica/admin/blob/master/meetings/2019-03-20.md)

**Comment by codeekage** [comment]
https://zoom.us/j/289168691
